export const UPDATE_TODO = "UPDATE_TODO";
export const ENABLE_EDIT_TODO = "ENABLE_EDIT_TODO";
export const UPDATE_SINGLE_TODO = "UPDATE_SINGLE_TODO";
export const DELETE_SINGLE_TODO = "DELETE_SINGLE_TODO";
export const ADD_NEW_TODO = "ADD_NEW_TODOS";
